version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meu-backend
    restart: always
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app
